package main

import (
	"context"
	"flag"
	"fmt"
	"math/rand"
	"time"

	"github.com/joho/godotenv"
	"go.uber.org/zap"

	"github.com/yourorg/atlasq/internal/config"
	"github.com/yourorg/atlasq/internal/logger"
	"github.com/yourorg/atlasq/internal/tasks"
)

func main() {
	var (
		emailCount  = flag.Int("email-count", 10, "Number of email tasks to create")
		reportCount = flag.Int("report-count", 5, "Number of report tasks to create")
		withFailures = flag.Bool("with-failures", false, "Include tasks that will fail for testing")
		withDelays   = flag.Bool("with-delays", false, "Include delayed tasks")
		verbose      = flag.Bool("verbose", false, "Verbose output")
	)
	flag.Parse()

	godotenv.Load()

	cfg, err := config.Load()
	if err != nil {
		panic(fmt.Sprintf("Failed to load config: %v", err))
	}

	zapLogger, err := logger.New("atlasq-seed", cfg.App.Version, cfg.App.Env)
	if err != nil {
		panic(fmt.Sprintf("Failed to create logger: %v", err))
	}

	client, err := tasks.NewClient(cfg)
	if err != nil {
		zapLogger.Fatal("Failed to create tasks client", zap.Error(err))
	}
	defer client.Close()

	ctx := context.Background()
	rand.Seed(time.Now().UnixNano())

	fmt.Printf("Seeding AtlasQ with tasks...\n")
	fmt.Printf("Email tasks: %d\n", *emailCount)
	fmt.Printf("Report tasks: %d\n", *reportCount)
	fmt.Printf("With failures: %v\n", *withFailures)
	fmt.Printf("With delays: %v\n", *withDelays)
	fmt.Println()

	var totalEnqueued int

	// Seed email tasks
	for i := 0; i < *emailCount; i++ {
		payload := generateEmailPayload(i, *withFailures)
		opts := generateEnqueueOptions(*withDelays)

		var result *tasks.EnqueueResult
		var err error

		if opts.Delay > 0 {
			result, err = client.EnqueueDelayed(ctx, tasks.TaskTypeSendEmail, payload, opts.Delay, opts)
		} else {
			result, err = client.EnqueueNow(ctx, tasks.TaskTypeSendEmail, payload, opts)
		}

		if err != nil {
			fmt.Printf("Failed to enqueue email task %d: %v\n", i+1, err)
			continue
		}

		totalEnqueued++
		if *verbose {
			fmt.Printf("Enqueued email task %d: ID=%s, Queue=%s, Delay=%v\n", 
				i+1, result.TaskID, result.Queue, opts.Delay)
		}
	}

	// Seed report tasks
	for i := 0; i < *reportCount; i++ {
		payload := generateReportPayload(i, *withFailures)
		opts := generateEnqueueOptions(*withDelays)

		var result *tasks.EnqueueResult
		var err error

		if opts.Delay > 0 {
			result, err = client.EnqueueDelayed(ctx, tasks.TaskTypeGenerateReport, payload, opts.Delay, opts)
		} else {
			result, err = client.EnqueueNow(ctx, tasks.TaskTypeGenerateReport, payload, opts)
		}

		if err != nil {
			fmt.Printf("Failed to enqueue report task %d: %v\n", i+1, err)
			continue
		}

		totalEnqueued++
		if *verbose {
			fmt.Printf("Enqueued report task %d: ID=%s, Queue=%s, Delay=%v\n", 
				i+1, result.TaskID, result.Queue, opts.Delay)
		}
	}

	fmt.Printf("\nSeeding complete!\n")
	fmt.Printf("Total tasks enqueued: %d\n", totalEnqueued)
	fmt.Printf("Check Asynqmon at http://localhost:8081 to see the tasks\n")
}

func generateEmailPayload(index int, withFailures bool) tasks.SendEmailPayload {
	domains := []string{"example.com", "test.org", "demo.net", "sample.io"}
	subjects := []string{
		"Welcome to AtlasQ!",
		"Your report is ready",
		"System notification",
		"Monthly newsletter",
		"Security alert",
		"Payment confirmation",
		"Account update",
		"Task completed",
	}
	
	domain := domains[rand.Intn(len(domains))]
	subject := subjects[rand.Intn(len(subjects))]
	
	// Add failure cases for testing
	if withFailures && rand.Float32() < 0.2 {
		if rand.Float32() < 0.5 {
			subject = "test-permanent-failure"
		} else {
			subject = "test-retryable-failure"
		}
	}

	return tasks.SendEmailPayload{
		To:      fmt.Sprintf("user%d@%s", index+1, domain),
		Subject: subject,
		Body:    fmt.Sprintf("This is a test email message #%d generated by the seed script. Time: %s", 
			index+1, time.Now().Format(time.RFC3339)),
	}
}

func generateReportPayload(index int, withFailures bool) tasks.GenerateReportPayload {
	reportTypes := []string{"sales", "analytics", "performance", "usage", "security", "financial"}
	reportType := reportTypes[rand.Intn(len(reportTypes))]
	
	reportID := fmt.Sprintf("%s-report-%d-%d", reportType, index+1, time.Now().Unix())
	
	// Add failure cases for testing
	if withFailures && rand.Float32() < 0.2 {
		if rand.Float32() < 0.5 {
			reportID = "test-permanent-failure"
		} else {
			reportID = "test-retryable-failure"
		}
	}

	return tasks.GenerateReportPayload{
		ReportID: reportID,
		Params: map[string]interface{}{
			"type":       reportType,
			"period":     "monthly",
			"format":     "pdf",
			"created_by": "seed-script",
			"timestamp":  time.Now().Format(time.RFC3339),
			"filters": map[string]interface{}{
				"date_range": map[string]string{
					"start": time.Now().AddDate(0, -1, 0).Format("2006-01-02"),
					"end":   time.Now().Format("2006-01-02"),
				},
				"include_charts": true,
				"include_tables": true,
			},
		},
	}
}

func generateEnqueueOptions(withDelays bool) *tasks.EnqueueOptions {
	queues := []string{tasks.QueueCritical, tasks.QueueDefault, tasks.QueueLow}
	weights := []float32{0.2, 0.6, 0.2} // Critical: 20%, Default: 60%, Low: 20%
	
	// Weighted random queue selection
	r := rand.Float32()
	var selectedQueue string
	cumulative := float32(0)
	for i, weight := range weights {
		cumulative += weight
		if r <= cumulative {
			selectedQueue = queues[i]
			break
		}
	}
	
	opts := &tasks.EnqueueOptions{
		Queue:    selectedQueue,
		MaxRetry: rand.Intn(8) + 3, // 3-10 retries
	}
	
	if withDelays && rand.Float32() < 0.3 {
		delays := []time.Duration{
			10 * time.Second,
			30 * time.Second,
			1 * time.Minute,
			2 * time.Minute,
			5 * time.Minute,
		}
		opts.Delay = delays[rand.Intn(len(delays))]
	}
	
	return opts
}